name: tests
on:
  pull_request:
    branches: [main]
jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.21"
      - name: Check out
        uses: actions/checkout@v4
      - name: Test
        run: go test ./... -cover
      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest
      - name: Check security
        run: gosec ./...
  style:
    name: style
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.21"
      - name: Check out
        uses: actions/checkout@v4
      - name: Format
        run: test -z $(go fmt ./...)
      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest
      - name: Analyze
        run: staticcheck ./...